version: '3'

services:
  dotnet-app:
    build: .
    ports: 
      - "10001:10001"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest" 
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "TestTest!"
      ACCEPT_EULA: "Y"